# @package _global_
dataset:
  # Central disease configuration - change this to switch diseases
  # Options: bpd, nec, rop, death, max_chole_TPNEHR (or their dated_ versions)
  target_disease: rop
  _target_: src.data.synthetic_neonatal.SyntheticNeonatalDatasetCollection
  name: synthetic_neonatal
  path: data/processed/autoregressive.csv  # Path to the CSV data file
  seed: ${exp.seed}  # Random seed for data splitting
  min_seq_length: 2  # Minimum sequence length to include in dataset
  max_seq_length: 30  # Maximum sequence length (truncates longer sequences)
  projection_horizon: 0  # Number of future steps to predict (0 = next timestep only)
  cf_seq_mode: sliding_treatment  # Counterfactual sequence generation mode
  val_batch_size: 512  # Batch size for validation/test sets
  treatment_mode: continuous  # Treatment type: continuous or binary
  vital_columns:
  - Alb_lab_value
  - Ca_lab_value
  - Cl_lab_value
  - CO2_lab_value
  - Glu_lab_value
  - K_lab_value
  - Mg_lab_value
  - Na_lab_value
  - PO4_lab_value
  - BUN_lab_value
  - Cr_lab_value
  - Tri_lab_value
  - ALKP_lab_value
  - ALT_lab_value
  - AST_lab_value
  - CaI_lab_value
  - day_since_birth
  - FluidDose
  - EnteralDose
  - days_on_TPN
  - TPNDose
  - TPNHours
  - ProtocolName_NEONATAL
  - LineID_2
  - FatProduct_SMOFlipid 20%
  - FatProduct_Intralipid 20%
  - FatProduct_Omegaven 10%
  - TodaysWeight
  static_columns:
  - gest_age
  - bw
  - gender_concept_id_8507
  - gender_concept_id_8532
  - race_concept_id_8515
  - race_concept_id_8516
  - race_concept_id_8527
  - race_concept_id_8557
  - race_concept_id_8657
  treatment_columns:
  - FatDose
  - AADose
  - DexDose
  - Acetate
  - Calcium
  - Copper
  - Famotidine
  - Levocar
  - Magnesium
  - MVITotal
  - Phosphate
  - Potassium
  - Sodium
  - Zinc
  - Chloride
  - GIR
  outcome_columns:
  - ${dataset.target_disease}  # Disease outcome to predict
  outcome_types:
  - binary  # Type of outcome: binary or continuous
  sequence_id_column: person_id  # Column identifying unique patients
  timestamp_column: days_on_TPN  # Column containing time information
  scaling: standard  # Feature scaling method: standard or minmax
  treatment_type: continuous  # Type of treatment features
  right_censor: true  # Apply right censoring based on disease date
  outcome_shift: 0  # Shift outcomes by n timesteps (for next-step prediction)
  last_timepoint_only: true  # Only use last timestep for loss (seq2one vs seq2seq)
  min_length_filter: true  # Filter out sequences shorter than min_seq_length
  one_seq_per_patient_eval: true  # Use one sequence per patient for evaluation
  split:
    val: 0.2
    test: 0.2
  task_weights:
    ${dataset.target_disease}: 1.0  # Weight for this task in multi-task learning
  use_gradnorm: false  # Enable GradNorm for automatic task weight balancing
  gradnorm_alpha: 1.5  # Alpha parameter for GradNorm (controls convergence speed)
  mute_decoder: true  # Zero out autoregressive inputs to prevent data leakage
model:
  dim_treatments: ???
  dim_vitals: ???
  dim_static_features: ???
  dim_outcomes:
  - 1
exp:
  unscale_rmse:
    disease: false
  percentage_rmse: false
